config/routes.rb
Server::Application.routes.draw do
  root :to => 'welcome#index'

  match 'signup' => 'users#new', :as => :signup
  match 'logout' => 'sessions#destroy', :as => :logout
  
  match 'login' => 'sessions#new', :as => :login
  
  match 'auth_token' => 'oauth#auth_token' 
  match 'access_token' => 'oauth#access_token'

  get 'authorise_app' => 'oauth#show_authorisation_dialog', :as => :authorise_app
  post 'authorise_app' => 'oauth#authorise_app', :as => :authorise_app

  resources :password_resets

  resources :sessions

  resources :users

end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/layouts/application.html.erb
<!doctype html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

        <title><%= content_for?(:title) ? yield(:title) : t('title.header') %></title>
        <%= stylesheet_link_tag    "application" %>
        <%= javascript_include_tag "application" %>
        <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Lobster" /> 
        <%= csrf_meta_tags %>
        <%= yield(:head) %>
    </head>
    <body>
      <header>
          <h1>AppName : Tag Line!</h1>
          <p>Your Application Description!</p>
      </header>
      <nav>
          <ul class="fancyNav">
            <li id="home"><%= link_to "Home", root_path, :class => "homeIcon" %></li>
            <% if current_user %>
            <li><a href="#">Option 1</a></li>
            <li><a href="#">Option 2</a></li>
            <li id="logout"><%= link_to "Logout", logout_url %></li>
            <% else %>
            <li id="login"><%= link_to "Login", login_url %></li>
            <li id="signup"><%= link_to "Sign up!", signup_url %></li>
            <% end %>
          </ul>
      </nav>
      <section id="main">
        <% flash.each do |name, msg| %>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        <% end %>
        <%= content_tag :h3, yield(:title) if show_title? %>
        <section id="content">
          <%= yield %>
        </section>
      </section>
      <footer>
        All the content on this website is copyright of Jais Cheema.
      </footer>
    </body>
</html>